# Build, test, publish, and upload a release of CoseSignTool
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pull Request and Continuous Integration Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
  release:

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            dir_command: gci -Recurse # If I don't like the output format, switch to Shell: cmd
            zip_command_debug: Compress-Archive -Path ./debug/ -DestinationPath CoseSignTool-Windows-debug.zip
            zip_command_release: Compress-Archive -Path ./release/ -DestinationPath CoseSignTool-Windows-release.zip
            command_shell: cmd
          - os: ubuntu-latest
            dir_command: ls -a -R
            zip_command_debug: zip -r CoseSignTool-Linux-debug.zip ./debug/
            zip_command_release: zip -r CoseSignTool-Linux-release.zip ./release/
            command_shell: bash
          - os: macos-latest
            dir_command: ls -a -R
            zip_command_debug: zip -r CoseSignTool-MacOS-debug.zip ./debug/
            zip_command_release: zip -r CoseSignTool-MacOS-release.zip ./release/
            command_shell: bash

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Build and Test debug
      # Use dotnet test to run Restore, Build, and Test, all in one sweep.
      run: dotnet test --verbosity normal CoseSignTool/CoseSignTool.sln
      #shell: bash
      
    - name: List working directory Windows
      # if: runner.os == 'Windows'
      run: ${{ matrix.dir_command }}

    # - name: List working directory non-Windows
    #   if: runner.os != 'Windows'  # TODO: Figure out how to set this in an environment variable so we only don't need separate steps.
    #   run: ${{ matrix.dir_command }}
      
  # The remaining steps run only when changes are pushed to Main, i.e., when a pull request completes.
  # While we could run the publish steps in a parallel job, having them here forces them to wait until the unit tests pass.
  # Another option to explore is to run them in a separate job that depands on ALL of the other jobs passing first.
  # Eventually we might want to tweak the CodeQL job to run on what we already built above so it isn't using resources to autobuild.
  
    - name: Publish outputs
      #if: ${{ github.event_name != 'pull_request' }}
      # Publish all of the non-test projects to published/release. We have to use the solution file to get the right output paths.
      run: |
        dotnet publish --no-build --configuration Debug --output published/debug CoseSignTool/CoseSignTool.sln
        dotnet publish --configuration Release --output published/release CoseSignTool/CoseSignTool.sln

    - name: Create zip files for release
      # if: ${{ github.event_name == 'release' }}
      run: |
        ${{ matrix.zip_command_debug }}
        ${{ matrix.zip_command_release }}
        # zip -r CoseSignTool-debug.zip ./debug/
        # zip -r CoseSignTool-release.zip ./release/
      working-directory: ./published

      # [IO.Compression.ZipFile]::CreateFromDirectory
              #upload_url=$(curl -sL https://api.github.com/repos/actions/checkout/releases/latest | jq -r '.upload_url')
        #echo UPLOAD_URL=$upload_url >> $GITHUB_ENV
                # zip -r CoseSignTool-debug.zip /home/runner/work/CoseSignTool/CoseSignTool/published/debug/
        # zip -r CoseSignTool-release.zip /home/runner/work/CoseSignTool/CoseSignTool/published/release/

    - name: List published directory Windows
      # if: ${{ github.event_name != 'pull_request' }}
      run: ${{ matrix.dir_command }}
      working-directory: ./published

    - name: Upload release artifacts
      #if: runner.os == 'Windows' # Need to re-test on other OS, but get linux working first
      #if: ${{ github.event_name == 'release' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./published/CoseSignTool-*.zip
        tag: v0.3.1
        file_glob: true #(turn this on if we want to upload all files in the directory)



      

