# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]  # Restore the others once it's working on Windows
        #os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Build and Test debug
      # Use dotnet test to run Restore, Build, and Test, all in one sweep.
      run: dotnet test --verbosity normal CoseSignTool/CoseSignTool.sln
      shell: bash
      
    - name: List working directory
      run: dir /b /a /s
      shell: cmd
      
    - name: Publish debug
      # Publish all of the non-test projects to the default location. 
      # Test projects are filtered out in the project files with the <IsPublishable>false</IsPublishable> attribute.
      # run: dotnet publish --no-build --configuration Debug CoseSignTool/CoseSignTool.sln
      run: dotnet publish --no-build --configuration Debug --output published/debug CoseSignTool/CoseSignTool/CoseSignTool.csproj
      
    - name: Publish release
      # Publish all of the non-test projects to the default location. 
      # Test projects are filtered out in the project files with the <IsPublishable>false</IsPublishable> attribute.
      run: dotnet publish --configuration Release --output published/release CoseSignTool/CoseSignTool/CoseSignTool.csproj

  #Publish:
   # name: publish-${{matrix.os}}
   # runs-on: ${{ matrix.os }}
   # strategy:
     # matrix:
       # os: [windows-latest]  # Restore the others once it's working on Windows
        #os: [windows-latest, ubuntu-latest, macOS-latest]
        
    #Run only when changes are pushed to Main, i.e., when a pull request completes.
    #if: ${{ github.event_name == 'push' }}
